services:
  - type: web
    name: og-soda-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: ENV
        value: staging
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: og_database_0vc9
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /health
    plan: free

